#define NB_ROOMS 16

static const int roomsSizes[16][2] = {
{5, 5},
{5, 7},
{5, 9},
{5, 11},
{7, 5},
{7, 7},
{7, 9},
{7, 11},
{9, 5},
{9, 7},
{9, 9},
{9, 11},
{11, 5},
{11, 7},
{11, 9},
{11, 11}
};

static const int rooms[16][11][11] = {
{
{WALL,DOOR,WALL,WALL,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,DOOR,WALL}
},
{
{WALL,WALL,WALL,WALL,WALL,WALL,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL},
{DOOR,FLOOR,FLOOR,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,DOOR,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,WALL,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,DOOR,WALL}
},
{
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,DOOR,WALL},
{WALL,FLOOR,FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,WALL,WALL},
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
{WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,DOOR,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,DOOR,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,DOOR},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
},
{
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{DOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},
{WALL,WALL,WALL,WALL,WALL,WALL,WALL,DOOR,WALL,WALL,WALL}
}
};